### ISSUE TITLE
ValueError: unstructured package not found, please install it with `pip install unstructured`

### ISSUE THREAD

**Issue by tsankar85** [prodramp/DeepWorks#1]
Team, 

I have followed and install packages available in requirements.txt file.
While running main.py code , facing an error. 

ModuleNotFoundError: No module named 'unstructured' 

I have tried to install unstructured thru pip, not successful many other package version dependencies. 

Please let me know if any other details.

Error Log :
**********
(prodramp) C:\Users\user1>python C:\prodramp\main.py
Traceback (most recent call last):
  File "C:\Users\user1\anaconda3\envs\prodramp\lib\site-packages\langchain\document_loaders\url.py", line 23, in __init__
    import unstructured  # noqa:F401
ModuleNotFoundError: No module named 'unstructured'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\prodramp\main.py", line 21, in <module>
    loader = UnstructuredURLLoader(urls=h2o_ai_wave_urls)
  File "C:\Users\user1\anaconda3\envs\prodramp\lib\site-packages\langchain\document_loaders\url.py", line 28, in __init__
    raise ValueError(
ValueError: unstructured package not found, please install it with `pip install unstructured`

**Comment by anishsoni29** [comment]
Did you try installing it in a designated environment like conda install instead of pip install?
